# Day 28 - Numpy Intro (Part 1)
NumPy (Numerical Python) is a powerful Python library used for numerical computations, especially with arrays and matrices.

🔹 Key Features:
* **ndarray**: Efficient multi-dimensional array object.
* **Broadcasting**: Perform operations on arrays of different shapes.
* **Mathematical Functions**: Fast element-wise operations.
* **Linear Algebra**: Built-in matrix operations, dot products, etc.
* **Random Module**: Random number generation.
For more check out the [official site](https://numpy.org/)

## Table of Content 
* [Installing & Importing library](#installing--importing-the-library)
* [Concept of Array](#concept-of-array)
  * [Why & where we need](#why-and-where-we-need-these-)
    * [1D Array](#-1d-array-vector)
    * [2D Array](#-2d-array-matrix)
    * [3D Array](#-3d-array-tensor)
* [Creating Arrays with Numpy](#creating-arrays-with-numpy)
  * [Initialize Array](#initialize-arrays)
* [Array Attributes](#array-attributes)


## Installing & importing the library 

* intall using command 
  * `pip install numpy `
* for importing
  * `import numpy as np`

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

## Concept of Array 
At the heart of NumPy is the ndarray (n-dimensional array), a fast, flexible container for large data sets in Python.
A NumPy array is a grid of values (all of the same data type) indexed by a tuple of non-negative integers.

It is more efficient than Python lists.
Supports vectorized operations (fast calculations without explicit loops).



In [9]:
# creating 1d array with range of 10

first_array = np.arange(10)
print(first_array)

print("First Array (1D) shape :  ",first_array.shape)

[0 1 2 3 4 5 6 7 8 9]
First Array (1D) shape :   (10,)


In [10]:
# creating 2d arrays
second_array=first_array[np.newaxis,:]
print(second_array)

print("Second Array (2D) shape ",second_array.shape)

[[0 1 2 3 4 5 6 7 8 9]]
Second Array (2D) shape  (1, 10)


In [11]:
# creating 3d arrays
third_array=second_array[np.newaxis,:]
print(third_array)

print("Third Array (3D) shape ",third_array.shape)

[[[0 1 2 3 4 5 6 7 8 9]]]
Third Array (3D) shape  (1, 1, 10)


### Why and where we need these ? 


#### 🔹 1D Array (Vector)
Structure: Single row or column
Shape: (n,)

📌 Use Cases:
* Storing features of a single data point: [height, weight, age]
* Working with simple lists of values: temperatures, scores, etc.
* Basic mathematical operations: dot products, sums



In [13]:
features = np.array([170, 65, 22])  # height, weight, age
print(features)
print(features.shape)

[170  65  22]
(3,)


#### 🔹 2D Array (Matrix)
Structure: Rows × Columns
Shape: (m, n)

📌 Use Cases:
* Dataset with multiple samples and features:
* Images in grayscale (height × width)
* Confusion matrix, transformation matrices in ML
* Tabular data (like Excel or CSV)

A 2D array means it has two dimensions: rows and columns, but the number of rows and columns can be anything.

🔹 A 2D array could be:
* 3 rows and 2 columns → shape: (3, 2)
* 2 rows and 5 columns → shape: (2, 5)
* 4 rows and 4 columns → shape: (4, 4)


In [18]:
dataset = np.array([
    [170, 65, 22],
    [180, 70, 24],
    [160, 55, 21]
])
dataset.shape

(3, 3)

#### 🔹 3D Array (Tensor)
Structure: Depth × Rows × Columns
Shape: (d, m, n)

📌 Use Cases:
* Colored images (RGB): Each image has 3 layers (R, G, B)
    * Shape: (height, width, 3)
* Multiple sequences of data (e.g. video frames, time series)
* Neural networks input data (batch size × features)
* NLP: Word embeddings across time steps

In [21]:

image = np.array([
  [[255, 0, 0], [0, 255, 0]],      # Row 1: Red, Green
  [[0, 0, 255], [255, 255, 0]]     # Row 2: Blue, Yellow
])

print(image.shape)  # Output: (2, 2, 3)


(2, 2, 3)


----

## Creating Arrays with Numpy

In [ ]:
a=np.array([1,24,3,4,5,6,7,8,9])  #1d array
b=np.array([(1,2,3),(4,5,6),(7,8,9)]) #2d array 

In [25]:
print("1D Array",a)
print(a.shape)
#---
print("2D Array",b)
print(b.shape)

1D Array [ 1 24  3  4  5  6  7  8  9]
(9,)
2D Array [[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


### initialize arrays


In [32]:
zeros=np.zeros((2,3)) # number of rows and coloumns

print(np.zeros((2,3)))
print(zeros.shape)

[[0. 0. 0.]
 [0. 0. 0.]]
(2, 3)


In [31]:
ones=np.ones((3,5))
print(ones)
print(ones.shape)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
(3, 5)


In [ ]:
full=np.full((2,3),5)  # 2 rows 3 coloumn => 5 will be printed
print(full) 


[[5 5 5]
 [5 5 5]]


In [ ]:
identity=np.eye(3)  # identity matrix
print(identity)
print(identity.shape)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
(3, 3)


## array Attributes

**1. ndim → Number of dimensions**

In [35]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.ndim)  # Output: 2

2


**2. shape → Dimensions of the array**

In [36]:
print(a.shape)  # Output: (2, 3)


(2, 3)


**3. size → Total number of elements**

In [37]:
print(a.size)  # Output: 6


6


**4. dtype → Data type of the elements**


In [38]:
print(a.dtype)  # Output: int64 (or int32 depending on your system)


int32


**5. T → Transpose of the array**

In [39]:
print(a.T)
# Output:
# [[1 4]
#  [2 5]
#  [3 6]]


[[1 4]
 [2 5]
 [3 6]]


 **6. reshape() → Change the shape without changing the data**

In [40]:
b = a.reshape((3, 2))
print(b)
# Output:
# [[1 2]
#  [3 4]
#  [5 6]]


[[1 2]
 [3 4]
 [5 6]]
