# Numpy(part2)

Earlier , we used the numpy library to understand its basics in  
* [Day 28 Numpy (part 1)](./Day28-Numpy(part1).ipynb)
* [Check out Numpy Library](https://pypi.org/project/numpy/)

* [Importing the library](#importing-the-library)
* [Creating Array ](#creating-array)
* [Type of Array ](#types-of-array)
* [One Dimension Array](#1d-array)
* [Concatenation](#concatenation)
* [Indexing & Slicing](#indexing-and-slcing)

## importing the library

In [2]:
import numpy as np

## Creating Array 
we can use different methods to create an array in Python. For instance,
* empty array with
* array using range
* arange function
* linspace function

In [3]:
#empty array with two elements
empty=np.empty((2,3))
print(empty)

[[3.33772792e-307 4.22786102e-307 2.78145267e-307]
 [4.00537061e-307 2.23419104e-317 0.00000000e+000]]


In [4]:
# making array using a range
x=np.arange(8)   # end range 
print(x)  # prints [0 1 2 3 4 5 6 7]

[0 1 2 3 4 5 6 7]


In [5]:
y=np.arange(2,10,2)  # starting from 2 end with 10 with step 2
print(y)

[2 4 6 8]


In [6]:
# specific difference between start and end
numbers=np.arange(0,100,10)
print(numbers)

[ 0 10 20 30 40 50 60 70 80 90]


linspace function 
create equally spaced number from defined raneg



In [7]:
lin=np.linspace(0,1,5)  #(numbers from 0-1 with 5 elements euqally spaced)
print(lin)

[0.   0.25 0.5  0.75 1.  ]


In [8]:
lin=np.linspace(0,1,num=100)   # (numbers from 0-1 with 100 elements euqally spaced)
print(lin)

[0.         0.01010101 0.02020202 0.03030303 0.04040404 0.05050505
 0.06060606 0.07070707 0.08080808 0.09090909 0.1010101  0.11111111
 0.12121212 0.13131313 0.14141414 0.15151515 0.16161616 0.17171717
 0.18181818 0.19191919 0.2020202  0.21212121 0.22222222 0.23232323
 0.24242424 0.25252525 0.26262626 0.27272727 0.28282828 0.29292929
 0.3030303  0.31313131 0.32323232 0.33333333 0.34343434 0.35353535
 0.36363636 0.37373737 0.38383838 0.39393939 0.4040404  0.41414141
 0.42424242 0.43434343 0.44444444 0.45454545 0.46464646 0.47474747
 0.48484848 0.49494949 0.50505051 0.51515152 0.52525253 0.53535354
 0.54545455 0.55555556 0.56565657 0.57575758 0.58585859 0.5959596
 0.60606061 0.61616162 0.62626263 0.63636364 0.64646465 0.65656566
 0.66666667 0.67676768 0.68686869 0.6969697  0.70707071 0.71717172
 0.72727273 0.73737374 0.74747475 0.75757576 0.76767677 0.77777778
 0.78787879 0.7979798  0.80808081 0.81818182 0.82828283 0.83838384
 0.84848485 0.85858586 0.86868687 0.87878788 0.88888889 0.89898

## Types of Array

In [9]:
# defin ethe data type of array
x=np.ones(2,dtype=int)
print(x)

[1 1]


## 1D Array 
* 1D array: A one-dimensional array is a collection of elements of the same data type stored in contiguous memory


In [10]:
x=np.ones(2,dtype=float)
print(x)

[1. 1.]


In [11]:
x=np.arange(10,dtype=float)
print(x)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In NumPy, the numbers in the dtype (data type) refer to the number of bits used to represent the value. Here's a brief overview of the differences:

**Integers**:

- int32: 32-bit signed integer, ranging from -2,147,483,648 to 2,147,483,647.
- int64: 64-bit signed integer, ranging from -9,223,372,036,854,775,808 to 9,223,372,036,854,775,807.

The main difference between int32 and int64 is the range of values they can represent. int64 can handle much larger numbers, but it also uses more memory.


**Floating-point numbers**:

- float16: 16-bit floating-point number, with a limited range and precision. It's often used for storage or transmission, rather than computation.
- float32: 32-bit floating-point number, commonly used for scientific computing and graphics. It provides a good balance between precision and memory usage.
- float64: 64-bit floating-point number, offering high precision and a wide range of values. It's often used for demanding numerical computations.

In [12]:
# sorting an array 
x=np.array([2,1,4,3,5])
print(x)
print("prinitng sorted array",np.sort(x))

[2 1 4 3 5]
prinitng sorted array [1 2 3 4 5]


there are also other ways to sort like argsort,lexsort

## Concatenation 

Concatenation 


In [13]:
# example of concatenation
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.concatenate((a,b))
print(c)  # prints [1 2 3 4 5 6]

[1 2 3 4 5 6]


conatenation of 2D array 
- like couple holding hands

In [14]:
# 2d array concatenation
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
print("printing a",a)
print("printing b",b)

c=np.concatenate((a,b))
print("after concatenation ", c)

printing a [[1 2 3]
 [4 5 6]]
printing b [[ 7  8  9]
 [10 11 12]]
after concatenation  [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


we can also work on 3d arrays



## Indexing and slcing 
Indexing is a way to access a subset of the elements in a list. You can use square brackets `[]` to specify the index or a slice of the list. A slice is a subset of the list specified by a range of indices.

In [17]:
a=np.array([1,2,3,4,5,6])
a


array([1, 2, 3, 4, 5, 6])

In [18]:
# accessing element 
a[2]


3

In [20]:
a [2:]

array([3, 4, 5, 6])

In [21]:
a[-1]

6