# Numpy(part2)

Earlier , we used the numpy library to understand its basics in  
* [Day 28 Numpy (part 1)](./Day28-Numpy(part1).ipynb)
* [Day 29 Numpy  (part2)](./Day29-Numpy(part2).ipynb)
* [Day 30 Numpy (part3)](Day30-Numpy(part3).ipynb)
----
* [Check out Numpy Library](https://pypi.org/project/numpy/)

**Table of Content** 

* [Creating Arrays from Data](#creating-arrays-from-data)
* [Creating Arrays with specific Data Types](#creating-arrays-with-specific-data-types)
* [Creating Array with Specific Shapes](#creating-arrays-with-specific-shapes)
* [Creating Arrays with Zeros, Ones, or Random values](#creating-arrays-with-zeros-ones-or-random-values)


In [2]:
import numpy as np

## Creating Arrays from Data
You can create a NumPy array from various types of data, such as:

- Lists: You can pass a list to the np.array() function to create an array.
- Tuples: Similar to lists, you can pass a tuple to the np.array() function.
- Other Arrays: You can create a new array from an existing array.


In [3]:
# creating array from a list 
my_list=[1,23,4,6,78]
arr=np.array(my_list)
print(arr)

[ 1 23  4  6 78]


In [4]:
# creating array from a tuple
tuple1 = (1, 2, 3, 4, 5)
array1 = np.array(tuple1)
print(array1)

[1 2 3 4 5]


In [5]:
# creating an array from another array
arr1 = np.array([1, 2, 3])
arr2 = np.array(arr1)
print(arr2)  # [1 2 3]


[1 2 3]


## Creating Arrays with Specific Data Types
You can specify the data type of the array elements using the dtype parameter:




In [6]:
# Create an array with integer data type
arr = np.array([1, 2, 3], dtype='int32')
print(arr.dtype)  # int32


int32


In [7]:
# Create an array with float data type
arr = np.array([1, 2, 3], dtype='float64')
print(arr.dtype)  # float64


float64


## Creating Arrays with Specific Shapes

You can create arrays with specific shapes using the reshape() function:


In [8]:
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape the array to 2D
arr = arr.reshape(2, 3)
print(arr)
# [[1 2 3]
#  [4 5 6]]



[[1 2 3]
 [4 5 6]]


## Creating Arrays with Zeros, Ones, or Random Values
You can create arrays filled with zeros, ones, or random values using the following functions:

- np.zeros(): Create an array filled with zeros.
- np.ones(): Create an array filled with ones.
- np.random.rand(): Create an array filled with random values.



In [9]:
# Create an array filled with zeros
arr = np.zeros((3, 3))
print(arr)
# [[0. 0. 0.]
#  [0. 0. 0.]
#  [0. 0. 0.]]



[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
# Create an array filled with ones
arr = np.ones((3, 3))
print(arr)
# [[1. 1. 1.]
#  [1. 1. 1.]
#  [1. 1. 1.]]


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [11]:

# Create an array filled with random values
arr = np.random.rand(3, 3)
print(arr)
# [[ random values ]]


[[0.96588574 0.79313076 0.81053198]
 [0.71947211 0.91696421 0.96204357]
 [0.17600542 0.53525243 0.86830321]]
