# Numpy(part2)

Earlier , we used the numpy library to understand its basics in  
* [Day 28 Numpy (part 1)](./Day28-Numpy(part1).ipynb)
* [Day 29 Numpy  (part2)](./Day29-Numpy(part2).ipynb)
* [Check out Numpy Library](https://pypi.org/project/numpy/)

In [8]:
import numpy as np

## Array Indexing & Slicing

* [Array Indexing](#array-indexing)
    * [1D Array Indexing](#1d-array-indexing)
    * [2D Array Indexing](#2d-array-indexing)
* [Array Slicing](#slicing-the-array)
    * [1D Array Slicing](#1d-array-slicing)
    * [2D Array Slicing](#2d-array-slicing)

# Array Indexing 
In NumPy, array indexing is used to access specific elements or groups of elements in an array. Indexing is 0-based, meaning that the first element is at index 0.



##  1D Array indexing  
- Accessing elements in a 1D array is straightforward.
- You can access an element at a specific index using the index value.
- For example, if you have a 1D array `arr` and you want to access the element at index 3, you can use `arr[3]`.
- Note that array indices in Python start at 0, so the first element in a 1D array is at index 0.
- You can also use negative indices to access elements from the end of the array.
- For example, `arr[-1]` will give you the last element in the
   array.

In [10]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [11]:

print(arr[0])  # Output: 1
print(arr[1])  # Output: 2
print(arr[-1])  # Output: 5 (negative indexing starts from the end)


1
2
5


In this example, arr[0] accesses the first element, arr[1] accesses the second element, and arr[-1] accesses the last element.


## 2D Array Indexing
In a 2D array, each element is identified by a pair of indices.you need to specify the row and column indices:


In [12]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr[0, 0])  # Output: 1
print(arr[0, 1])  # Output: 2
print(arr[1, 2])  # Output: 6


1
2
6


In this example, arr[0, 0] accesses the element at row 0, column 0, and arr[1, 2] accesses the element at row 1, column 2.


## Slicing the array
Slicing is a technique used to extract a subset of elements from a sequence, such as a string, list, or array. It allows you to access a range of elements by specifying the start and end indices.



**Slicing Syntax**

The general syntax for slicing is:

sequence[start:stop:step]

Where:

- start: The starting index of the slice (inclusive).
- stop: The ending index of the slice (exclusive).
- step: The increment between elements in the slice (default is 1).


## 1D Array Slicing
In Python, you can use the following syntax to slice a 1D array:


In [13]:
arr = np.array([1, 2, 3, 4, 5])

print(arr[1:3])  # Output: [2, 3]
print(arr[:3])  # Output: [1, 2, 3]
print(arr[2:])  # Output: [3, 4, 5]
print(arr[:])  # Output: [1, 2, 3, 4, 5]



[2 3]
[1 2 3]
[3 4 5]
[1 2 3 4 5]


In anbove example:

- arr[1:3] extracts elements from index 1 to 2 (stop index is exclusive).
- arr[:3] extracts elements from the start to index 2.
- arr[2:] extracts elements from index 2 to the end.
- arr[:] extracts all elements.


## 2D Array Slicing
For 2D arrays, you can slice rows and columns separately:


In [14]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr[1:, 1:])  # Output: [[5, 6], [8, 9]]
print(arr[:, 1])  # Output: [2, 5, 8]
print(arr[1, :])  # Output: [4, 5, 6]


[[5 6]
 [8 9]]
[2 5 8]
[4 5 6]


- arr[1:, 1:] extracts rows from index 1 to the end and columns from index 1 to the end.
- arr[:, 1] extracts the second column.
- arr[1, :] extracts the second row.
